# first-server은 별칭    
upstream first-server {
    # app1은 서비스명
    server app1:80;
}

# second-server는 별칭
upstream second-server {
    # app2는 서비스명
    server app2:80;
}

server {
    listen 80;
    server_name localhost;

    location /app1 {
        proxy_pass http://first-server/;  
    }

    location /app2 {
        proxy_pass http://second-server/;
    }
}
