# 캐시 관련 설정(캐시 저장 디렉토리, 캐시 이름 설정)
proxy_cache_path /var/cache/nginx keys_zone=my_cache:10m;

server {
    listen 80;

    location / {
        proxy_pass http://host.docker.internal:5000;
        proxy_cache off;                              # 캐시 사용하지 않음
    }

    location = /image.png {
        proxy_pass http://host.docker.internal:5000;
        proxy_cache my_cache;                         # proxy_cache_path에서 설정한 캐시 사용
        proxy_cache_valid 200 1m;                     # 200 상태 응답 1분동안 캐시
        add_header X-Cache-Status $upstream_cache_status always; # reponse 헤더에 캐시 여부 표시
		proxy_ignore_headers Cache-Control Expires; # 백엔드의 캐시 정책을 무시하고 Nginx가 캐시
    }
}
