services:
  app1:
    build:
      context: ./app1
    networks:
      - mynetwork
  app2:
    build:
      context: ./app2
    networks:
      - mynetwork
  lb:
    ports:
      - 80:80
    build:
      context: ./lb
    networks:
      - mynetwork

networks:
  mynetwork: